### PR TITLE
add adminmanage file

### PR DESCRIPTION
**Pull request by Maidiep372**
check admin mangage...

### CODE REVIEW

**Comment by Maidiep372** [comment]
[Admin: Quản Lí Admin](https://trello.com/c/C8MViUVG/12-admin-qu%E1%BA%A3n-l%C3%AD-admin)

**Comment by DucThien21** [comment]
[Admin: Quản Lí User](https://trello.com/c/u6R7Hyts/13-admin-qu%E1%BA%A3n-l%C3%AD-user)

**Comment by DucThien21** [comment]
[Admin: Quản Lí User](https://trello.com/c/u6R7Hyts/13-admin-qu%E1%BA%A3n-l%C3%AD-user)

**Comment by DucThien21** [comment]
[Admin: Quản Lí User](https://trello.com/c/u6R7Hyts/13-admin-qu%E1%BA%A3n-l%C3%AD-user)

**Comment by DucThien21** [comment]
[Admin: Chuyên Mục](https://trello.com/c/F0HS2DqY/14-admin-chuy%C3%AAn-m%E1%BB%A5c)

**Pull request closed without merging**
